artifact_location: file:///c:/Users/arkha/OneDrive/Desktop/EdgeAI/Weapon_Detection/Modelling_and_Evaluation/runs/mlflow/799503439405754221
creation_time: 1741861996280
experiment_id: '799503439405754221'
last_update_time: 1741861996280
lifecycle_stage: active
name: /Shared/Ultralytics
