artifact_location: file:///c:/Users/arkha/OneDrive/Desktop/EdgeAI/Weapon_Detection/Modelling_and_Evaluation/runs/mlflow/775520396219015359
creation_time: 1741634940239
experiment_id: '775520396219015359'
last_update_time: 1741634940239
lifecycle_stage: active
name: /Shared/Ultralytics
