artifact_location: file:///c:/Users/arkha/OneDrive/Desktop/EdgeAI/Weapon_Detection/Modelling_and_Evaluation/runs/mlflow/0
creation_time: 1741634940105
experiment_id: '0'
last_update_time: 1741634940105
lifecycle_stage: active
name: Default
